-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- Link to schema: https://app.quickdatabasediagrams.com/#/d/pBjxyx
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.

-- Modify this code to update the DB schema diagram.
-- To reset the sample schema, replace everything with
-- two dots ('..' - without quotes).

CREATE TABLE IF NOT EXISTS Films (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100)   NOT NULL,
    description varchar(100)   NOT NULL,
    releaseDate date   NOT NULL,
    duration integer   NOT NULL,
    mpa integer,
    CONSTRAINT pk_Films PRIMARY KEY (
        id
     )
);

CREATE TABLE IF NOT EXISTS Users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(100)   NOT NULL,
    login varchar(100)   NOT NULL,
    name varchar(100)   NOT NULL,
    birthday date   NOT NULL,
    CONSTRAINT pk_Users PRIMARY KEY (
        id
     )
);

CREATE TABLE IF NOT EXISTS likes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id integer   NOT NULL,
    user_id integer   NOT NULL,
    CONSTRAINT pk_likes PRIMARY KEY (
        id
     )
);

CREATE TABLE IF NOT EXISTS Genres (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100)   NOT NULL,
    CONSTRAINT pk_Genres PRIMARY KEY (
        id
     )
);

CREATE TABLE IF NOT EXISTS Films_Genres_Link (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id integer   NOT NULL,
    genre_id integer   NOT NULL,
    CONSTRAINT pk_Films_Genres_Link PRIMARY KEY (
        id
     )
);

CREATE TABLE IF NOT EXISTS Friends (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer   NOT NULL,
    friend_id integer   NOT NULL,
    CONSTRAINT pk_Friends PRIMARY KEY (
        id
     )
);

CREATE TABLE IF NOT EXISTS mpa (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    CONSTRAINT pk_mpa PRIMARY KEY (
            id
         )
);


ALTER TABLE likes ADD CONSTRAINT IF NOT EXISTS fk_likes_film_id FOREIGN KEY(film_id)
REFERENCES Films (id);

ALTER TABLE likes ADD CONSTRAINT IF NOT EXISTS fk_likes_user_id FOREIGN KEY(user_id)
REFERENCES Users (id);

ALTER TABLE Films_Genres_Link ADD CONSTRAINT IF NOT EXISTS fk_Films_Genres_Link_film_id FOREIGN KEY(film_id)
REFERENCES Films (id);

ALTER TABLE Films_Genres_Link ADD CONSTRAINT IF NOT EXISTS fk_Films_Genres_Link_genre_id FOREIGN KEY(genre_id)
REFERENCES Genres (id);

ALTER TABLE Friends ADD CONSTRAINT IF NOT EXISTS fk_Friends_user_id FOREIGN KEY(user_id)
REFERENCES Users (id);

ALTER TABLE Friends ADD CONSTRAINT IF NOT EXISTS fk_Friends_friend_id FOREIGN KEY(friend_id)
REFERENCES Users (id);

ALTER TABLE films ADD CONSTRAINT IF NOT EXISTS fk_mpa_film_id FOREIGN KEY(mpa)
REFERENCES mpa (id);

DELETE FROM films_genres_link;
DELETE FROM likes;
DELETE FROM Friends;
DELETE FROM films;
DELETE FROM users;
--DELETE FROM GENRES;
--DELETE FROM MPA;


--DELETE FROM ;
--DELETE FROM ;


DELETE FROM GENRES;
INSERT INTO GENRES (id, name) VALUES (1, 'Комедия');
INSERT INTO GENRES (id, name) VALUES (2, 'Драма');
INSERT INTO GENRES (id, name) VALUES (3, 'Мультфильм');
INSERT INTO GENRES (id, name) VALUES (4, 'Триллер');
INSERT INTO GENRES (id, name) VALUES (5, 'Документальный');
INSERT INTO GENRES (id, name) VALUES (6, 'Боевик');

DELETE FROM MPA;
INSERT INTO MPA (id, name) VALUES(1,'G');
INSERT INTO MPA (id, name) VALUES(2,'PG');
INSERT INTO MPA (id, name) VALUES(3,'PG-13');
INSERT INTO MPA (id, name) VALUES(4,'R');
INSERT INTO MPA (id, name) VALUES(5,'NC-17');


--DROP TABLE rating_mpa;
--DROP TABLE likes;
--DROP TABLE films_genres_link;
--DROP TABLE genres;
--DROP TABLE friends;
--DROP TABLE films;
--DROP TABLE users;